# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'volta-cli/action@v4'
        with:
          node-version: '22.4.1'
          yarn-version: '1.22.22'

      - uses: 'actions/cache@v4'
        id: cache-install
        with:
          path: |
            node_modules
            **/node_modules
          key: install-22.4.1-${{ hashFiles('yarn.lock', '.github/workflows/ci.yml', 'examples/*/yarn.lock', 'packages/*/package.json', 'packages/*/yarn.lock') }}

      - uses: 'actions/cache@v4'
        id: cache-build
        with:
          # Note: the tree-sitter-xpath .js and .wasm paths are standard for
          # tree-sitter's build output. They also litter a bunch of other files
          # in various build phases, several under `src` (which is why the
          # grammar's TypeScript source is not there).
          path: |
            examples/*/dist
            packages/*/dist
            packages/tree-sitter-xpath/grammar.js
            packages/tree-sitter-xpath/src/grammar.json
            packages/tree-sitter-xpath/src/parser.c
            packages/tree-sitter-xpath/src/tree_sitter/parser.h
            packages/tree-sitter-xpath/tree-sitter-xpath.wasm
            packages/tree-sitter-xpath/types
          key: build-22.4.1-${{ github.sha }}

      # `@getodk/xpath` tests (currently) expect this time zone
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ env.TZ }}
          timezoneMacos: ${{ env.TZ }}
          timezoneWindows: ${{ env.TZ }}

      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn build --force'

      - name: Build Web Forms
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          yarn workspace @getodk/web-forms build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./packages/web-forms/dist-demo/